[general]
resolution = [768, 768]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true
bucket_no_upscale = true

[[datasets]]
image_directory = "/home/pyro/datasets/lucyv2"
cache_directory = "/home/pyro/models/_out/h3/cache/lucyv2"
num_repeats = 1
