[prompt]
width = 1024
height = 1024
frame_count = 1
sample_steps = 20

[[prompt.subset]]
prompt = "a woman"
seed = 42

[[prompt.subset]]
prompt = "a skinny and pretty gothik woman doing a selfie video for tik tok"
seed = 43
